# Generated by Django 3.0.7 on 2020-06-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('group_ref', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=1200)),
            ],
        ),
        migrations.DeleteModel(
            name='UserMpdel',
        ),
    ]
